flowchart TD
  %% activity:AD-UC001 uc:UC-001
  subgraph PART-UC001-001["Посетитель"]
  ADN-UC001-002["Просмотреть описание мероприятия"]
  ADN-UC001-003["Отправить имя и email для регистрации"]
  end
  subgraph PART-UC001-002["Система"]
  ADN-UC001-004["Проверить email на повторную регистрацию"]
  ADN-UC001-005{"Email уже зарегистрирован?"}
  ADN-UC001-006["Подтвердить регистрацию"]
  ADN-UC001-007["Не допустить повторную регистрацию email"]
  end
  ADN-UC001-001(("start"))
  ADN-UC001-008(("end"))
  ADN-UC001-001 -->|"Старт просмотра мероприятия"| ADN-UC001-002
  ADN-UC001-002 -->|"Описание просмотрено"| ADN-UC001-003
  ADN-UC001-003 -->|"Имя и email отправлены"| ADN-UC001-004
  ADN-UC001-004 -->|"Проверка выполнена"| ADN-UC001-005
  ADN-UC001-005 -->|"[email не зарегистрирован ранее]"| ADN-UC001-006
  ADN-UC001-005 -->|"[email уже зарегистрирован ранее]"| ADN-UC001-007
  ADN-UC001-006 -->|"Регистрация подтверждена"| ADN-UC001-008
  ADN-UC001-007 -->|"Повторная регистрация отклонена"| ADN-UC001-008
