flowchart TD
  %% activity:AD-UC002 uc:UC-002
  subgraph PART-UC002-001["Сотрудник кафе"]
  ADN-UC002-001(("start"))
  ADN-UC002-002["Открыть экран очереди приготовления"]
  ADN-UC002-003["Выбрать заказ в очереди"]
  ADN-UC002-004["Изменить статус заказа на «принят»"]
  ADN-UC002-005{"Статус изменён на «принят»?"}
  ADN-UC002-006["Изменить статус заказа на «готовится»"]
  ADN-UC002-007{"Статус изменён на «готовится»?"}
  ADN-UC002-008["Изменить статус заказа на «готов»"]
  ADN-UC002-009{"Статус изменён на «готов»?"}
  ADN-UC002-010["Изменить статус заказа на «выдан»"]
  ADN-UC002-011{"Статус изменён на «выдан»?"}
  ADN-UC002-012["Показать причину отказа"]
  ADN-UC002-013(("end"))
  end
  ADN-UC002-001 --> ADN-UC002-002
  ADN-UC002-002 --> ADN-UC002-003
  ADN-UC002-003 --> ADN-UC002-004
  ADN-UC002-004 --> ADN-UC002-005
  ADN-UC002-005 -->|"да"| ADN-UC002-006
  ADN-UC002-005 -->|"нет"| ADN-UC002-012
  ADN-UC002-006 --> ADN-UC002-007
  ADN-UC002-007 -->|"да"| ADN-UC002-008
  ADN-UC002-007 -->|"нет"| ADN-UC002-012
  ADN-UC002-008 --> ADN-UC002-009
  ADN-UC002-009 -->|"да"| ADN-UC002-010
  ADN-UC002-009 -->|"нет"| ADN-UC002-012
  ADN-UC002-010 --> ADN-UC002-011
  ADN-UC002-011 -->|"да"| ADN-UC002-013
  ADN-UC002-011 -->|"нет"| ADN-UC002-012
  ADN-UC002-012 --> ADN-UC002-013
