flowchart TD
  %% activity:AD-UC002 uc:UC-002
  subgraph PART-UC002-001["Система"]
  ADN-UC002-001(("start"))
  ADN-UC002-002["Передача заявки на одобрение"]
  ADN-UC002-006{"Слияние"}
  ADN-UC002-007["Сохранение решения в журнале одобрений"]
  ADN-UC002-008(("end"))
  end
  subgraph PART-UC002-002["Ответственный сотрудник"]
  ADN-UC002-003{"Заявка одобрена?"}
  ADN-UC002-004["Одобрение заявки"]
  ADN-UC002-005["Заявка не одобрена"]
  end
  ADN-UC002-001 --> ADN-UC002-002
  ADN-UC002-002 --> ADN-UC002-003
  ADN-UC002-003 -->|"[одобрено]"| ADN-UC002-004
  ADN-UC002-003 -->|"[не одобрено]"| ADN-UC002-005
  ADN-UC002-004 --> ADN-UC002-006
  ADN-UC002-005 --> ADN-UC002-006
  ADN-UC002-006 --> ADN-UC002-007
  ADN-UC002-007 --> ADN-UC002-008
