flowchart TD
  %% activity:AD-UC003 uc:UC-003
  subgraph PART-UC003-001["Клиент"]
  ADN-UC003-001(("start"))
  ADN-UC003-002["Добавить позицию в корзину"]
  ADN-UC003-004["Изменить количество позиции"]
  ADN-UC003-005["Удалить позицию из корзины"]
  end
  subgraph PART-UC003-002["Система"]
  ADN-UC003-003["Обновить корзину"]
  ADN-UC003-006{"Изменение корзины успешно?"}
  ADN-UC003-007["Сохранить состояние корзины"]
  ADN-UC003-008["Показать сообщение об ошибке"]
  ADN-UC003-009(("end"))
  end
  ADN-UC003-001 --> ADN-UC003-002
  ADN-UC003-002 --> ADN-UC003-003
  ADN-UC003-003 --> ADN-UC003-004
  ADN-UC003-004 --> ADN-UC003-005
  ADN-UC003-005 --> ADN-UC003-006
  ADN-UC003-006 -->|"да"| ADN-UC003-007
  ADN-UC003-006 -->|"нет"| ADN-UC003-008
  ADN-UC003-007 --> ADN-UC003-009
  ADN-UC003-008 --> ADN-UC003-009
