flowchart TD
  %% activity:AD-UC008 uc:UC-008
  subgraph PART-UC008-001["Сотрудник кафе"]
  ADN-UC008-001(("start"))
  ADN-UC008-002["Выбрать заказ"]
  ADN-UC008-004["Изменить статус заказа"]
  end
  subgraph PART-UC008-002["Система"]
  ADN-UC008-003["Показать доступные действия"]
  ADN-UC008-005{"Изменение допустимо?"}
  ADN-UC008-006["Сохранить новый статус"]
  ADN-UC008-007["Показать сообщение об ошибке"]
  ADN-UC008-008(("end"))
  end
  ADN-UC008-001 --> ADN-UC008-002
  ADN-UC008-002 --> ADN-UC008-003
  ADN-UC008-003 --> ADN-UC008-004
  ADN-UC008-004 --> ADN-UC008-005
  ADN-UC008-005 -->|"да"| ADN-UC008-006
  ADN-UC008-005 -->|"нет"| ADN-UC008-007
  ADN-UC008-006 --> ADN-UC008-008
  ADN-UC008-007 --> ADN-UC008-008
