flowchart TD
  %% activity:AD-UC006 uc:UC-006
  subgraph PART-UC006-001["Система"]
  ADN-UC006-001(("start"))
  ADN-UC006-002["Присвоить заказу номер"]
  ADN-UC006-003["Сформировать подтверждение"]
  ADN-UC006-004{"Подтверждение сформировано?"}
  ADN-UC006-005["Показать подтверждение"]
  ADN-UC006-006["Показать сообщение об ошибке"]
  ADN-UC006-007(("end"))
  end
  ADN-UC006-001 --> ADN-UC006-002
  ADN-UC006-002 --> ADN-UC006-003
  ADN-UC006-003 --> ADN-UC006-004
  ADN-UC006-004 -->|"да"| ADN-UC006-005
  ADN-UC006-004 -->|"нет"| ADN-UC006-006
  ADN-UC006-005 --> ADN-UC006-007
  ADN-UC006-006 --> ADN-UC006-007
