flowchart TD
  %% activity:AD-UC002 uc:UC-002
  subgraph PART-UC002-001["Клиент"]
  ADN-UC002-001(("start"))
  ADN-UC002-002["Выбрать позицию меню"]
  ADN-UC002-004["Выбрать обязательный размер"]
  ADN-UC002-005["Выбрать доступные модификаторы"]
  end
  subgraph PART-UC002-002["Система"]
  ADN-UC002-003["Показать размеры и модификаторы"]
  ADN-UC002-006{"Обязательный размер выбран?"}
  ADN-UC002-007["Зафиксировать выбор"]
  ADN-UC002-008["Показать сообщение об ошибке"]
  ADN-UC002-009(("end"))
  end
  ADN-UC002-001 --> ADN-UC002-002
  ADN-UC002-002 --> ADN-UC002-003
  ADN-UC002-003 --> ADN-UC002-004
  ADN-UC002-004 --> ADN-UC002-005
  ADN-UC002-005 --> ADN-UC002-006
  ADN-UC002-006 -->|"да"| ADN-UC002-007
  ADN-UC002-006 -->|"нет"| ADN-UC002-008
  ADN-UC002-007 --> ADN-UC002-009
  ADN-UC002-008 --> ADN-UC002-009
