flowchart TD
  %% activity:AD-UC005 uc:UC-005
  subgraph PART-UC005-001["Клиент"]
  ADN-UC005-001(("start"))
  ADN-UC005-002["Ввести имя"]
  ADN-UC005-003["Ввести номер телефона"]
  ADN-UC005-004["Нажать кнопку отправки заказа"]
  end
  subgraph PART-UC005-002["Система"]
  ADN-UC005-005{"Данные валидны?"}
  ADN-UC005-006["Отправить заказ"]
  ADN-UC005-007["Показать сообщение об ошибке"]
  ADN-UC005-008(("end"))
  end
  ADN-UC005-001 --> ADN-UC005-002
  ADN-UC005-002 --> ADN-UC005-003
  ADN-UC005-003 --> ADN-UC005-004
  ADN-UC005-004 --> ADN-UC005-005
  ADN-UC005-005 -->|"да"| ADN-UC005-006
  ADN-UC005-005 -->|"нет"| ADN-UC005-007
  ADN-UC005-006 --> ADN-UC005-008
  ADN-UC005-007 --> ADN-UC005-008
