flowchart TD
  %% activity:AD-UC002 uc:UC-002
  subgraph PART-UC002-001["Посетитель"]
  ADN-UC002-001(("start"))
  ADN-UC002-002["Отправить имя и email"]
  end
  subgraph PART-UC002-002["Система регистрации"]
  ADN-UC002-003["Проверить email на повторную регистрацию"]
  ADN-UC002-004{"Email уже зарегистрирован?"}
  ADN-UC002-005["Сохранить регистрацию без email в журналах в открытом виде"]
  ADN-UC002-006["Отобразить подтверждение регистрации"]
  ADN-UC002-007["Отклонить регистрацию и сообщить о дубликате email"]
  ADN-UC002-008{"Объединение"}
  ADN-UC002-009(("end"))
  end
  ADN-UC002-001 --> ADN-UC002-002
  ADN-UC002-002 --> ADN-UC002-003
  ADN-UC002-003 --> ADN-UC002-004
  ADN-UC002-004 -->|"[email не зарегистрирован]"| ADN-UC002-005
  ADN-UC002-004 -->|"[email уже зарегистрирован]"| ADN-UC002-007
  ADN-UC002-005 --> ADN-UC002-006
  ADN-UC002-006 --> ADN-UC002-008
  ADN-UC002-007 --> ADN-UC002-008
  ADN-UC002-008 --> ADN-UC002-009
