flowchart TD
  %% activity:AD-UC002 uc:UC-002
  subgraph PART-UC002-001["Система LabSlot"]
  ADN-UC002-001(("start"))
  ADN-UC002-002["Передача заявки на одобрение"]
  ADN-UC002-005["Запись одобрения в журнал"]
  ADN-UC002-007{"Объединение"}
  ADN-UC002-008(("end"))
  end
  subgraph PART-UC002-002["Ответственный сотрудник"]
  ADN-UC002-003["Рассмотрение заявки"]
  ADN-UC002-004{"Заявка одобрена?"}
  ADN-UC002-006["Отклонение заявки"]
  end
  ADN-UC002-001 --> ADN-UC002-002
  ADN-UC002-002 --> ADN-UC002-003
  ADN-UC002-003 --> ADN-UC002-004
  ADN-UC002-004 -->|"[одобрено]"| ADN-UC002-005
  ADN-UC002-004 -->|"[отклонено]"| ADN-UC002-006
  ADN-UC002-005 --> ADN-UC002-007
  ADN-UC002-006 --> ADN-UC002-007
  ADN-UC002-007 --> ADN-UC002-008
